blogs/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('blogs.views',
    url(r'^$', 'postlist'),
    url(r'^(?P<post_id>\d+)/$', 'postpage'),
)

contact/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('contact.views',
    url(r'^$', 'contact'),
    url(r'^thanks/', 'thanks'),
)

labs/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('labs.views',
    url(r'^$', 'landing'),
    url(r'^publicip/', 'publicip'),
)

mysite/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import *
#from django.views.generic.simple import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',  TemplateView.as_view(template_name='index3.html')),
    url(r'^project/', include('projects.urls', namespace="projects")),
    url(r'^contact/', include('contact.urls', namespace="contact")),
    url(r'^blog/', include('blogs.urls', namespace="blogs")),
    url(r'^lab/', include('labs.urls', namespace="labs")),
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

projects/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('projects.views',
    url(r'^$', 'projlist'),
    url(r'^(?P<proj_id>\d+)/$', 'projpage'),
)

blogs/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateField('date created')
    def __unicode__(self):
        return self.title

contact/models.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, help_text='100 characters max.')
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField(help_text='Must be a valid address.')
    # attachment = forms.FileField(required=False)
    cc_myself = forms.BooleanField(required=False)

labs/models.py
from django.db import models
from django import forms

class Table(models.Model):
    title = models.CharField(max_length=200)
    key = models.CharField(max_length=100)
    ip = models.GenericIPAddressField()
    port = models.PositiveIntegerField()
    def __unicode__(self):
        return self.title

class KeyForm(forms.Form):
    key = forms.CharField(widget=forms.PasswordInput(), max_length=100)

class Lab(models.Model):
    title = models.CharField(max_length=100)
    filename = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    icon_address = models.CharField(max_length=100)
    created = models.DateField('date created')
    def __unicode__(self):
        return self.title

projects/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=200)
    comp_date = models.DateTimeField('date completed')
    subtitle = models.CharField(max_length=200)
    description = models.CharField(max_length=1000)
    tech_skills = models.CharField(max_length=1000)
    def __unicode__(self):
        return self.title

class Link(models.Model):
    project = models.ForeignKey(Project)
    address = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    def __unicode__(self):
        return self.title

class Picture(models.Model):
    project = models.ForeignKey(Project)
    address = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    def __unicode__(self):
        return self.address

class Video(models.Model):
    project = models.ForeignKey(Project)
    embed = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    def __unicode__(self):
        return self.title

blogs/views.py
from django.shortcuts import render, render_to_response
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse
from blogs.models import Post
from django.http import Http404

def postlist(request):
    posts = Post.objects.all().order_by("-created")
    paginator = Paginator(posts, 2)

    try:
        page = int(request.GET.get("page", '1'))
    except ValueError: 
        page = 1

    try:
        posts = paginator.page(page)
    except (InvalidPage, EmptyPage):
        posts = paginator.page(paginator.num_pages)

    return render_to_response("postlist.html", {'posts':posts})

def postpage(request, post_id):
    try:
        post = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        raise Http404
    return render(request, 'postpage.html', {'post': post})

contact/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from contact.models import ContactForm
from django.core.context_processors import csrf

def contact(request):
    if request.method == 'POST': # If the form has been submitted...
        form = ContactForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']
            
            recipients = ['babraham42@gmail.com']
            if cc_myself:
                recipients.append(sender)
            from django.core.mail import send_mail
            subject = subject + " [" + sender + "]"
            send_mail(subject, message, sender, recipients)

            return HttpResponseRedirect('/contact/thanks/') # Redirect after POST
    else:
        form = ContactForm() # An unbound form

    #context = RequestContext(request, {'form':form})
    context = {'form':form}
    context.update(csrf(request))
    return render_to_response('contacts.html', context)

def thanks(request):
    return render_to_response('thanks.html')

labs/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect, Http404
from ipware.ip import get_real_ip
from labs.models import Table, KeyForm, Lab
from django.views.decorators.csrf import csrf_exempt
import json

def landing(request):
    labs = Lab.objects.all().order_by("title")[:]
    context = {'labs':labs}
    return render(request, 'landing.html', context)

def publicip(request):
    return HttpResponse( json.dumps({'ip':get_ip(request)}), content_type="application/json" )

@csrf_exempt
def key_input(request):
    if request.method == 'POST': # If the form has been submitted...
        form = KeyForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            table_key = form.cleaned_data['key']

            # check validity of the table key
            tables = Table.objects.all().filter(key=table_key)
            if not tables or len(tables) != 1:
                raise Http404
            
            table = tables[0]
            context = {'table':table}
            return render_to_response('websocket.html', context)
    else:
        form = KeyForm() # An unbound form

    context = {'form':form}
    return render_to_response('landing.html', context)

def get_ip(request):
    real_ip = get_real_ip(request)
    if real_ip is not None:
        return str(real_ip)
    else:
        return 'None'

projects/views.py
from django.http import Http404
from django.shortcuts import render
from projects.models import Project

# Create your views here.
def projlist(request):
    latest_proj_list = Project.objects.all().order_by('-comp_date')[:]
    for proj in latest_proj_list:
        pics = proj.picture_set.all()
        if pics:
            proj.picture_address = pics[0]
        else:
            proj.picture_address = 'sheep.png'

    context = {'latest_proj_list':latest_proj_list}
    return render(request, 'projlist.html', context)

def projpage(request, proj_id):
    try:
        proj = Project.objects.get(pk=proj_id)
    except Project.DoesNotExist:
        raise Http404
    return render(request, 'projpage2.html', {'proj': proj})

blogs/templates/postlist.html
{% extends "navbar2.html" %}
{% block body %}

<div class="container">

<!-- Posts  -->
    <ul>
        {% for post in posts.object_list %}
            <div class="title">
            	<h3>{{ post.title }}</h3>
            </div>
            <ul>
                <div class="time">
                	<p><em>{{ post.created }}</em></p>
                </div>
                <div class="body">
                	<pre>{{ post.body }}</pre>
                </div>
            </ul>
        {% endfor %}
    </ul>

    <!-- Next/Prev page links  -->
    {% if posts.object_list and posts.paginator.num_pages > 1 %}
    <div class="pagination" style="margin-top: 20px; margin-left: -20px; ">
        <span class="step-links">
            {% if posts.has_previous %}
                <a href= "?page={{ posts.previous_page_number }}">newer entries &lt;&lt; </a>
            {% endif %}

            <span class="current">
                &nbsp;Page {{ posts.number }} of {{ posts.paginator.num_pages }}
            </span>

            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}"> &gt;&gt; older entries</a>
            {% endif %}
        </span>
    </div>
    {% endif %}


</div>

{% endblock %}

blogs/templates/postpage.html
{% extends "navbar2.html" %}
{% block body %}

<div class="container">

<!-- Posts  -->
    <div class="title">
        <h3>{{ post.title }}</h3>
    </div>
    <ul>
        <div class="time">
            <p><em>{{ post.created }}</em></p>
        </div>
        <div class="body">
            <pre>{{ post.body }}</pre>
        </div>
    </ul>

</div>

{% endblock %}

contact/templates/contacts.html
{% extends "navbar2.html" %}
{% block body %}

<div class="container">

<br />
<h1>Resources</h1>
<br />

<div class="row">
  <div class="col-sm-6 col-md-2">
    <div class="thumbnail">
      <br />
      <img src="/media/resume_icon.png" alt="resume">
      <div class="caption">
        <h3>Resume</h3>
        <p>
          <a href="https://goo.gl/7oqRXv" class="btn btn-primary" role="button" target="_blank">Download</a> 
          <br /><br />

          <!-- <a href="https://goo.gl/7oqRXv" class="btn btn-default" role="button" onclick="window.print();return false;">Print</a> -->
          <iframe id="iFramePdf" src="/media/Abraham_Bereket_Resume.pdf" style="display:none;"></iframe>
          <a href="#" class="btn btn-default" role="button" onclick="var getMyFrame = document.getElementById('iFramePdf');getMyFrame.focus();getMyFrame.contentWindow.print();" >Print</a>

          <br /><br />
          <a href="https://goo.gl/#analytics/goo.gl/7oqRXv/all_time" class="btn btn-warning" role="button" target="_blank">Click Stats</a>
          <br />
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-2">
    <div class="thumbnail">
      <br />
      <img src="/media/linkedin_icon.png" alt="LinkedIn">
      <div class="caption">
        <h3>LinkedIn</h3>
        <p>
          <a href="https://www.linkedin.com/in/bereketabraham" class="btn btn-primary" role="button" target="_blank">Open</a>
          <br />
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-2">
    <div class="thumbnail">
      <br />
      <img src="/media/github_icon.png" alt="GitHub">
      <div class="caption">
        <h3>GitHub</h3>
        <p>
          <a href="https://github.com/babraham123" class="btn btn-primary" role="button" target="_blank">Open</a>
          <br /><br />
          <a href="http://ghv.artzub.com/#user=babraham123" class="btn btn-warning" role="button" target="_blank">Commit Stats</a>
          <br />
        </p>
      </div>
    </div>
  </div>
</div>
<br /><br />

<div class="panel panel-default">
  <div class="panel-body">
    <h1>Send me an email:</h1>
    <br />

    <div class="row">
      <div class="col-sm-6 col-md-10">  
        <form action="." method="post">{% csrf_token %}
          {{ form.non_field_errors }}
          
          <div class="fieldWrapper">
            {{ form.sender.errors }}
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Your Address</span>
              <input id="id_sender" name="sender" type="email" class="form-control" placeholder="person@example.com" aria-describedby="basic-addon1" />
            </div>
          </div>
          
          <div class="fieldWrapper">
            {{ form.subject.errors }}
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Subject</span>
              <input id="id_subject" maxlength="100" name="subject" type="text" class="form-control" placeholder="Big news" aria-describedby="basic-addon1" />
            </div>
          </div>
          
          <div class="fieldWrapper">
            {{ form.message.errors }}
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Body</span>
              <textarea cols="40" id="id_message" name="message" rows="10" class="form-control" placeholder="Tell me about your..." aria-describedby="basic-addon1" ></textarea>
            </div>
          </div>

          <div class="fieldWrapper">
            {{ form.cc_myself.errors }}
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">CC Yourself?</span>
              <input id="id_cc_myself" name="cc_myself" type="checkbox" class="form-control" aria-describedby="basic-addon1" />
            </div>
          </div>
          <br />
          <p><input type="submit" value="Send message" class="btn btn-success" /></p>
        </form>
      </div>
    </div>

  </div>
</div>

</div>
{% endblock %}

contact/templates/thanks.html
{% extends "navbar2.html" %}
{% block body %}

<div class="container">

<br>
<br>
<br>
<h1>Thanks for emailing! I'll get back to you soon.</h1>

</div>
{% endblock %}

labs/templates/landing.html
{% extends "navbar2.html" %}
{% block body %}

<div class="container-fluid">

<br/>
<h1>Experiments in Web Technologies</h1>
<br/>

{% if labs %}
	<div class="row-fluid">
		<div class="col-xs-12 center">
		{% for lab in labs %}
			<div class="col-xs-5 jumbotron">
				<h2><a href="{{ lab.filename }}">{{ lab.title }}</a></h2>
				<p><i>{{ lab.description }}</i></p>
				<!-- <img src="/media/{{ lab.icon_address }}" alt="{{ lab.title }}"/> -->
			</div>
			<div class="col-xs-1"></div>
		{% endfor %}
		</div>
	</div>

{% else %}
	<br>
	<p>This site is currently under construction.</p>
{% endif %}


</div>
{% endblock %}

labs/templates/websocket.html
{% extends "navbar2.html" %}
{% block body %}

<br />
<h1>{{ table.title }}</h1>
<br />
<h3>Messages: <span id="words"></span></h3>
<br />
<h3>Incoming data: <span id="words2"></span></h3>

<br />
<p>
	<button class="btn btn-primary" id="connect" style="margin-right:20px">Connect to Server</button>
	<button class="btn btn-danger" id="close">Close</button>
</p>
<br />

<textarea class="span12" id="data_input" rows="6">
000:FF0000 001:00FF00 002:0000FF
</textarea>

<p>
	<button class="btn btn-default" id="mode1" style="padding-right:10px">Mode 1</button>
	<button class="btn btn-default" id="mode2" style="padding-right:10px">Mode 2</button>
	<button class="btn btn-default" id="mode3" style="padding-right:10px">Mode 3</button>
	<button class="btn btn-default" id="mode4" style="padding-right:10px">Mode 4</button>
</p>
<br />
<p><button class="btn btn-success" id="send">Send Data</button></p>


<script type="text/javascript">
	// transfer data from django to javascript
	var data = {};
	data.ip = "{{ table.ip }}";
	data.port = "{{ table.port }}";
</script>
<script src="/static/websocket.js"></script>

{% endblock %}

labs/templates/websocket_test.html
{% extends "navbar2.html" %}
{% block body %}

<br />
<h2 id="words">Hi! This is the start of the websockets test.</h2>
<br />
<h3 id="words2">empty</h3>

<br />
<p><button type="button" id="connect">Connect to Server</button></p>
<br />
<p><button type="button" id="send">Send Data</button></p>
<br />
<p><button type="button" id="sendjson">Send JSON</button></p>
<br />
<p><button type="button" id="close">Close</button></p>

<script type="text/javascript">
  var ip = {{ ip }};
</script>
<script src="/static/websocket_test.js"></script>

{% endblock %}

projects/templates/projlist.html
{% extends "navbar2.html" %}
{% block body %}

<div class="container">
<br />
{% if latest_proj_list %}
	{% for proj in latest_proj_list %}
		<div class="row">
			<div class="col-md-5">
				<a href="/project/{{ proj.id }}/">
					<img class="img-responsive" src="/media/{{ proj.picture_address }}" alt="">
				</a>
			</div>
			<div class="col-md-7 jumbotron">
				<h3>{{ proj.title }}</h3>
				<h4>{{ proj.subtitle }}</h4>
				<a class="btn btn-primary" href="/project/{{ proj.id }}/">View Project <span class="glyphicon glyphicon-chevron-right"></span></a>
			</div>
		</div>

	{% endfor %}

{% else %}
	<br>
	<p>This site is currently under construction.</p>
{% endif %}

</div>

{% endblock %}

projects/templates/projpage.html
{{ proj }}
{{  proj.subtitle }}

projects/templates/projpage2.html
{% extends "navbar2.html" %}
{% block body %}

<div class="container">
	<div class="row">
		<div class="speaker">
			<h1>{{ proj.title }}</h1>
			<h3><i>{{ proj.subtitle }}</i></h3>
			<b>Completion Date: {{ proj.comp_date }}</b>
		</div>
	</div>
	<div class="row">
		<div class="span6">
			<br>
			<p>{{ proj.description }}</p>
			<br>
			<p>{{ proj.tech_skills | safe }}</p>
			<br>

			{% for link in proj.link_set.all %}
			<h3><a href="{{ link.address }}" target="_blank">{{ link.title | safe}}</a></h3>
			<br>
			{% endfor %}

		</div>
	</div>


	<div class="row">
	{% for video in proj.video_set.all %}
		<div class="col-md-6">
			<iframe width="420" height="315" src="{{ video.embed }}" frameborder="0" rel="0" allowfullscreen></iframe>
			<h4>{{ video.title }}</h4>
		</div>
	{% endfor %}
	</div>

	<div class="row">
	{% for picture in proj.picture_set.all %}
		<div class="col-md-6">
			<a href="#">
				<img class="img-responsive" src="/media/{{ picture.address }}" alt="">
			</a>
			<h4>{{ picture.title }}</h4>
		</div>
	{% endfor %}
	</div>

</div>

{% endblock %}


templates/index.html
<h1>Welcome to my website!</h1>
<h2>Bereket Abraham</h2>

<p>Cheers for getting this far, really.</p>

templates/index2.html
{% extends "navbar.html" %}
{% block body %}

	<div id="frontpage-content">
		<div id="frontpage-intro">
			<p> --- Hi, I'm a Mechanical and Aerospace engineer currently attending Princeton University. I am also completing certificates, or minors, in Applied Mathematics, Computer Science, and Robotics. My fascination with the connection between computing and engineering is reflected in my coursework, as well as in the projects I have pursued on my own time. --- </p>
		</div><!--end frontpage-info-->
		<div id="featured-projects">
			<h3>Featured Projects</h3>
			<div id="featured-projects-bg">

			<!-- THIS IS THE FEATURED SECTION - UPLOAD SCREENSHOTS TO THE "IMAGES" FOLDER (390x190PX IN SIZE) - THEN ADD THE URL TO THE SCREENSHOTS BELOW -->
				<a href="/project/1/" title="Computational Fluid Dynamics"><img class="featured-project-image" src="/media/pic1.png" alt="Computational Fluid Dynamics"/></a>	
				<a href="/project/2/" title="Engine Analysis"><img class="featured-project-image" src="/media/pic2.png" alt="Engine Analysis" /></a>

			</div>
		</div>
	</div>

{% endblock %}

templates/index3.html
{% extends "navbar2.html" %}
{% block body %}

<style type="text/css">
	body {

	background: url(/static/background1.jpg) no-repeat center center fixed;
	background-position: 50% 50%;
	background-height: 100%;
	background-repeat: no-repeat;
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	background-size: cover;
	}

	.container {
	background-color: rgba(0,0,0, 0.5);
	color:white;
	text-align: left;
	}
	.hero-unit {
	background: none;
	}
	.imgborder {
	border-width: 2px;
	border-color: Black;
	}
</style>


<div class="container">
  <div class="hero-unit" id="splashtext">
    <h1>Bereket Abraham</h1>

    <div class="row-fluid">
    <div class="span6">
			<br>
			<p>
I'm currently employed as a software engineer. I have degrees in Mechanical Engineering from Carnegie Mellon University and Princeton University. My interests include data pipelines, automation and robotics.
<br />
Finally, in my free time I experiment with micro controllers and build out small web apps on the internet. If you want to learn more, <a href="/contact/">download my resume</a> or check out some of my <a href="/project/">featured projects</a>.

	        </div>
		<div class="span5 offset1">
			<a href="/project/6/"><img src="/media/3d_display.jpg" alt="3D Volumetric Display"/></a>
			<br>
			<a href="/project/1/"><img src="/media/vortex_street.png" alt="Lagrangian Coherent Structures" /></a>
		</div>
	</div>
  </div>



</div> <!-- /container -->

{% endblock %}

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>The Engineer</title>
		<link rel="stylesheet" type="text/css" href="/static/style2.css" />
		<script type="text/javascript" src="/static/jquery-1.8.3.min.js"></script>
		
		<link rel="icon" href="/media/favicon.ico" type="image/x-icon" />
		<link rel="shortcut icon" href="/media/favicon.ico" type="image/x-icon" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">


<!-- Google Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-72307749-1', 'auto');
  ga('send', 'pageview');

</script>

	</head>

	<body>
		<div id="wrap">
		<div id="header">
			<a href="/"><h1>[ BEREKET ABRAHAM ]</h1></a>       	
			<h2>[Mechanical Engineer]</h2>
			<div id="nav">
			<ul id="nav-pages">
				<li><a href="/">Home</a></li>
				<li><a href="/project/">Projects</a></li>
				<li><a href="/project/7/">Resume</a></li>
				<li><a href="/contact/">Contact</a></li>
			</ul>
			</div>
		</div>
		<div id="content">
			{% block body %}{% endblock %}
		</div>

		<div id="footer">
			<p>[Abraham Industries] All Rights Reserved</p>
		</div>
		</div>
	</body>	
	
</html>

templates/navbar2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>The Engineer</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Professional website.">
  <meta name="author" content="Bereket Abraham">

  <link rel="icon" href="/static/favicon.ico" type="image/x-icon" >
  <link rel="shortcut icon" href="/static/favicon.ico" type="image/x-icon" >

  <!-- styles -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

  <link rel=stylesheet type=text/css href="/static/mod.css">
  <link rel=stylesheet type=text/css href="/static/personal.css">
  <link rel=stylesheet type=text/css href="/static/blog.css">

  <!-- javascript -->
  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script>
  $(document).ready(function () {
      var url = $(location).attr('href');
      console.log(url);
      $('.nav-custom li').each(function( index ) {
          var link = $(this).children('a').attr('href');
          console.log(link);

          if (url.indexOf(link) >= 0) {
              $('.nav-custom li.active').removeClass('active');
              $(this).addClass('active');
          }
      });
  });
  </script>

<!-- Google Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-72307749-1', 'auto');
  ga('send', 'pageview');

</script>
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top nav-custom" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">BEREKET ABRAHAM</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">HOME</a></li>
        <li><a href="/contact/">RESUME</a></li>
        <li><a href="/project/">PROJECTS</a></li>
        <li><a href="/lab/">EXPERIMENTS</a></li>
        <li><a href="/blog/">BLOG</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <div class="container">
  {% block body %}{% endblock %}
</div>

</body>